package ca.udem.maville.client.users;

public enum Quartier {
    AHUNTSIC_CARTIERVILLE,
    ANJOU,
    COTE_DES_NEIGES_NOTRE_DAME_DE_GRACE,
    LACHINE,
    LASALLE,
    LE_PLATEAU_MONT_ROYAL,
    LE_SUD_OUEST,
    MERCIER_HOCHELAGA_MAISONNEUVE,
    MONTREAL_NORD,
    OUTREMONT,
    PIERREFONDS_ROXBORO,
    RIVIERE_DES_PRAIRIES_POINTE_AUX_TREMBLES,
    ROSEMONT_LA_PETITE_PATRIE,
    SAINT_LAURENT,
    SAINT_LEONARD,
    VERDUN,
    VILLE_MARIE,
    VILLERAY_SAINT_MICHEL_PARC_EXTENSION
}
