package ca.udem.maville.client;

public enum TypeTravaux {
    TRAVAUX_ROUTIERS,
    GAZ_OU_ELECTRICITE,
    CONSTRUCTION_RENOVATION,
    ENTRETIEN_PAYSAGER,
    TRANSPORT_EN_COMMUN,
    SIGNALISATION_ECLAIRAGE,
    TRAVAUX_SOUTERRAINS,
    TRAVAUX_RESIDENTIELS,
    ENTRETIEN_URBAIN,
    TELECOMMUNICATIONS
}

