name: Re-build les images docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code de la branche main
        uses: actions/checkout@v3

      - name: Build backend
        run: docker build -t backend ./backend

      - name: Build client
        run: docker build -t client ./client