name: Compiler et tester

on:
  push:
    branches:
      - main     # exécuter dès qu'il y a un push sur main
  pull_request:
    branches:
      - main      # exécuter dès qu'il y a une pull request sur main

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Recuperation du code de la branche main
        uses: actions/checkout@v3

      - name: Initialisation de Java
        uses: actions/setup-java@v3
        with: 
          java-version: '21'
          distribution: 'temurin'

      - name: Compilation du code avec Maven
        run: cd backend && mvn clean compile 

      - name: Passer les tests unitaires
        run: cd backend && mvn test
